retriever:
  model_name_or_path: openbmb/MiniCPM-Embedding-Light
  backend_configs:
    infinity:
      bettertransformer: false
      pooling_method: auto
      model_warmup: false
      trust_remote_code: true
    sentence_transformers:
      trust_remote_code: true
      sentence_transformers_encode:
        normalize_embeddings: false
        encode_chunk_size: 256
        q_prompt_name: query
        psg_prompt_name: document
        psg_task: null
        q_task: null
    openai:
      model_name: text-embedding-v4
      base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api_key: sk-5230
    bm25:
      lang: en
      save_path: index/bm25
  batch_size: 16
  corpus_path: /home/dhj/vsworkspace/ultrarag/ui/backend/chunck_all.jsonl
  gpu_ids: '1'
  is_multimodal: false
  backend: openai
  index_backend: milvus
  index_backend_configs:
    faiss:
      index_use_gpu: true
      index_chunk_size: 10000
      index_path: index/index.index
    milvus:
      uri: tcp://127.0.0.1:29901
      token: null
      id_field_name: id
      vector_field_name: vector
      text_field_name: contents
      id_max_length: 64
      text_max_length: 60000
      metric_type: IP
      index_params:
        index_type: AUTOINDEX
        metric_type: IP
      search_params:
        metric_type: IP
        params: {}
      index_chunk_size: 1000
  is_demo: true
  collection_name: my_data
  embedding_path: embedding/embedding.npy
  overwrite: false
